apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  containers:
    - name: master
      image: 10.15.99.209:8082/k8s-redis:1.0
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
    - name: sentinel
      image: 10.15.99.209:8082/k8s-redis:1.0
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
